### ISSUE TITLE
prepqm input incombatible with pandas >2.0.0

### ISSUE THREAD

**Issue by FloSeu** [bharurn/mimicpy#40]
With pandas >2.0, the DataFrame.append() function, that was previously deprecated, was removed. Therefore, in the preqpm utility, the following error is produced when selecting atoms:
```

 	                ***** MiMiCPy *****                  

 	                Running version 0.2.1
	For more information type mimicpy [subcommand] --help 

=====> Running prepqm <=====


**Reading topology**


**Reading coordinates**  \Done

Please enter selection below. For more information type 'help'
> add (resname is LEU) and (resid is 364) and (name is C)
Traceback (most recent call last):
  File "/home/hildilab/anaconda3/envs/mimic/bin/mimicpy", line 8, in <module>
    sys.exit(main())
  File "/home/hildilab/anaconda3/envs/mimic/lib/python3.9/site-packages/mimicpy/__main__.py", line 761, in main
    args.func(args)
  File "/home/hildilab/anaconda3/envs/mimic/lib/python3.9/site-packages/mimicpy/__main__.py", line 225, in prepqm
    if check_user_input(user_input) == False:
  File "/home/hildilab/anaconda3/envs/mimic/lib/python3.9/site-packages/mimicpy/__main__.py", line 157, in check_user_input
    dispatch[command](selection)
  File "/home/hildilab/anaconda3/envs/mimic/lib/python3.9/site-packages/mimicpy/core/prepare.py", line 56, in add
    self.__qm_atoms = self.__qm_atoms.append(qdf)
  File "/home/hildilab/anaconda3/envs/mimic/lib/python3.9/site-packages/pandas/core/generic.py", line 6296, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

```

**Comment by bharath-raghavan** [comment]
Thank for your interest in MiMiCPy and MiMiC. This repo has moved to https://gitlab.com/mimic-project/mimicpy.
However, the issue you stated is still valid in the new repo. If you have a GitLab account, please repost the issue there: https://gitlab.com/mimic-project/mimicpy/-/issues/
